import { useCallback, useEffect, useMemo, useState } from 'react';
import { BarChart3, CalendarDays, Factory, Plus, RefreshCw, Scale, Truck } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { cabecalhoPerfil } from '../../utils/apiAuth';

const API_URL = import.meta.env.VITE_API_URL ?? '';
type Safra = { SafraId: number; Nome: string; Inicio: string; Fim: string | null; Ativa: boolean };
type Lancamento = { LancamentoId: number; SafraId: number; SafraNome: string; Dia: string; Toneladas: number; CustoOperacional: number; EquipamentoId: number | null; Origem: string; Observacao: string | null };
type Resumo = Safra & { Toneladas: number; Custo: number; CustoPorTonelada: number | null; Lancamentos: number };
type Dados = { safras: Safra[]; lancamentos: Lancamento[]; resumo: Resumo[] };
const moeda = (valor: number | null | undefined) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(valor ?? 0));
const data = (valor: string) => valor ? new Date(`${valor.slice(0, 10)}T12:00:00`).toLocaleDateString('pt-BR') : '—';
const hoje = new Date().toISOString().slice(0, 10);

export function ProducaoBatata() {
  const { usuario } = useAuth();
  const [dados, setDados] = useState<Dados | null>(null); const [erro, setErro] = useState<string | null>(null); const [carregando, setCarregando] = useState(true); const [salvando, setSalvando] = useState(false);
  const [safra, setSafra] = useState({ nome: '', inicio: hoje, fim: '' }); const [lancamento, setLancamento] = useState({ safraId: '', dia: hoje, toneladas: '', custoOperacional: '', equipamentoId: '', observacao: '' });
  const carregar = useCallback(async () => { setCarregando(true); try { const resposta = await fetch(`${API_URL}/api/producao/batata`, { headers: cabecalhoPerfil(usuario?.perfil) }); const corpo = await resposta.json(); if (!resposta.ok) throw new Error(corpo.error); setDados(corpo); setErro(null); } catch (falha) { setErro(falha instanceof Error ? falha.message : 'Falha ao carregar Produção/Batata.'); } finally { setCarregando(false); } }, [usuario?.perfil]);
  useEffect(() => { carregar(); }, [carregar]);
  const total = useMemo(() => (dados?.resumo ?? []).reduce((acumulado, item) => ({ toneladas: acumulado.toneladas + Number(item.Toneladas ?? 0), custo: acumulado.custo + Number(item.Custo ?? 0) }), { toneladas: 0, custo: 0 }), [dados]);
  const custoTon = total.toneladas ? total.custo / total.toneladas : null;
  const criarSafra = async (evento: React.FormEvent) => { evento.preventDefault(); setSalvando(true); setErro(null); try { const resposta = await fetch(`${API_URL}/api/producao/batata`, { method: 'POST', headers: { ...cabecalhoPerfil(usuario?.perfil), 'Content-Type': 'application/json' }, body: JSON.stringify({ acao: 'safra', ...safra }) }); const corpo = await resposta.json(); if (!resposta.ok) throw new Error(corpo.error); setSafra({ nome: '', inicio: hoje, fim: '' }); await carregar(); } catch (falha) { setErro(falha instanceof Error ? falha.message : 'Não foi possível criar a safra.'); } finally { setSalvando(false); } };
  const criarLancamento = async (evento: React.FormEvent) => { evento.preventDefault(); setSalvando(true); setErro(null); try { const resposta = await fetch(`${API_URL}/api/producao/batata`, { method: 'POST', headers: { ...cabecalhoPerfil(usuario?.perfil), 'Content-Type': 'application/json' }, body: JSON.stringify({ acao: 'lancamento', safraId: Number(lancamento.safraId), dia: lancamento.dia, toneladas: Number(lancamento.toneladas), custoOperacional: Number(lancamento.custoOperacional), equipamentoId: lancamento.equipamentoId ? Number(lancamento.equipamentoId) : null, observacao: lancamento.observacao }) }); const corpo = await resposta.json(); if (!resposta.ok) throw new Error(corpo.error); setLancamento({ safraId: '', dia: hoje, toneladas: '', custoOperacional: '', equipamentoId: '', observacao: '' }); await carregar(); } catch (falha) { setErro(falha instanceof Error ? falha.message : 'Não foi possível registrar a produção.'); } finally { setSalvando(false); } };
  return <div className="space-y-6 pb-12 max-w-7xl"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Produção / Batata</p><h1 className="text-2xl font-bold text-slate-800">Painel de Produção</h1><p className="mt-1 text-sm text-slate-500">Acompanhe toneladas, custo operacional e custo por tonelada por safra.</p></div><button onClick={carregar} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white"><RefreshCw size={16} className={carregando ? 'animate-spin' : ''} />Atualizar</button></header>
    {erro && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{erro}</div>}
    <section className="grid grid-cols-1 gap-4 sm:grid-cols-3"><Kpi icone={<Scale size={19} />} rotulo="Produção registrada" valor={`${total.toneladas.toLocaleString('pt-BR', { maximumFractionDigits: 3 })} t`} apoio="Somatório das safras cadastradas" /><Kpi icone={<Factory size={19} />} rotulo="Custo operacional" valor={moeda(total.custo)} apoio="Lançado manualmente ou pela frota" /><Kpi icone={<BarChart3 size={19} />} rotulo="Custo por tonelada" valor={custoTon === null ? 'Sem produção' : moeda(custoTon)} apoio="Custo operacional ÷ toneladas" /></section>
    <section className="grid grid-cols-1 gap-5 xl:grid-cols-2"><form onSubmit={criarSafra} className="rounded-2xl border bg-white p-5"><h2 className="flex items-center gap-2 font-bold text-slate-800"><CalendarDays size={18} className="text-emerald-600" />Nova safra</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input required value={safra.nome} onChange={(e) => setSafra({ ...safra, nome: e.target.value })} placeholder="Ex.: Safra Batata 2026" className="rounded-xl border px-3 py-2.5 text-sm sm:col-span-2" /><label className="text-xs font-medium text-slate-600">Início<input required type="date" value={safra.inicio} onChange={(e) => setSafra({ ...safra, inicio: e.target.value })} className="mt-1 block w-full rounded-xl border px-3 py-2.5 text-sm" /></label><label className="text-xs font-medium text-slate-600">Fim (opcional)<input type="date" value={safra.fim} onChange={(e) => setSafra({ ...safra, fim: e.target.value })} className="mt-1 block w-full rounded-xl border px-3 py-2.5 text-sm" /></label></div><button disabled={salvando} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Plus size={16} />Cadastrar safra</button></form>
      <form onSubmit={criarLancamento} className="rounded-2xl border bg-white p-5"><h2 className="flex items-center gap-2 font-bold text-slate-800"><Truck size={18} className="text-emerald-600" />Colheita e transporte</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><select required value={lancamento.safraId} onChange={(e) => setLancamento({ ...lancamento, safraId: e.target.value })} className="rounded-xl border px-3 py-2.5 text-sm sm:col-span-2"><option value="">Selecione a safra</option>{dados?.safras.map((item) => <option key={item.SafraId} value={item.SafraId}>{item.Nome}</option>)}</select><label className="text-xs font-medium text-slate-600">Data<input required type="date" value={lancamento.dia} onChange={(e) => setLancamento({ ...lancamento, dia: e.target.value })} className="mt-1 block w-full rounded-xl border px-3 py-2.5 text-sm" /></label><label className="text-xs font-medium text-slate-600">Toneladas<input required min="0.001" step="0.001" type="number" value={lancamento.toneladas} onChange={(e) => setLancamento({ ...lancamento, toneladas: e.target.value })} className="mt-1 block w-full rounded-xl border px-3 py-2.5 text-sm" /></label><label className="text-xs font-medium text-slate-600">Custo operacional<input required min="0" step="0.01" type="number" value={lancamento.custoOperacional} onChange={(e) => setLancamento({ ...lancamento, custoOperacional: e.target.value })} className="mt-1 block w-full rounded-xl border px-3 py-2.5 text-sm" /></label><label className="text-xs font-medium text-slate-600">Código do equipamento (opcional)<input type="number" value={lancamento.equipamentoId} onChange={(e) => setLancamento({ ...lancamento, equipamentoId: e.target.value })} className="mt-1 block w-full rounded-xl border px-3 py-2.5 text-sm" /></label><input value={lancamento.observacao} onChange={(e) => setLancamento({ ...lancamento, observacao: e.target.value })} placeholder="Observação (opcional)" className="rounded-xl border px-3 py-2.5 text-sm sm:col-span-2" /></div><button disabled={salvando || !dados?.safras.length} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Plus size={16} />Registrar produção</button></form></section>
    <section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="font-bold text-slate-800">Comparativo por safra</h2><p className="mt-1 text-sm text-slate-500">O custo por tonelada é exibido somente quando há toneladas registradas.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-3">Safra</th><th className="p-3">Período</th><th className="p-3 text-right">Toneladas</th><th className="p-3 text-right">Custo</th><th className="p-3 text-right">R$/t</th><th className="p-3 text-right">Lançamentos</th></tr></thead><tbody>{(dados?.resumo ?? []).map((item) => <tr key={item.SafraId} className="border-t"><td className="p-3 font-semibold text-slate-800">{item.Nome}{item.Ativa && <span className="ml-2 rounded-full bg-emerald-50 px-2 py-0.5 text-[10px] text-emerald-700">Ativa</span>}</td><td className="p-3 text-slate-600">{data(item.Inicio)} — {item.Fim ? data(item.Fim) : 'em andamento'}</td><td className="p-3 text-right">{Number(item.Toneladas).toLocaleString('pt-BR', { maximumFractionDigits: 3 })} t</td><td className="p-3 text-right">{moeda(item.Custo)}</td><td className="p-3 text-right font-bold text-emerald-700">{item.CustoPorTonelada === null ? '—' : moeda(item.CustoPorTonelada)}</td><td className="p-3 text-right">{item.Lancamentos}</td></tr>)}{!carregando && !dados?.resumo.length && <tr><td className="p-8 text-center text-slate-400" colSpan={6}>Nenhuma safra cadastrada.</td></tr>}</tbody></table></div></section>
    <section className="overflow-hidden rounded-2xl border bg-white"><div className="border-b p-5"><h2 className="font-bold text-slate-800">Últimos lançamentos</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-3">Data</th><th className="p-3">Safra</th><th className="p-3 text-right">Toneladas</th><th className="p-3 text-right">Custo</th><th className="p-3">Origem</th><th className="p-3">Observação</th></tr></thead><tbody>{(dados?.lancamentos ?? []).map((item) => <tr key={item.LancamentoId} className="border-t"><td className="p-3">{data(item.Dia)}</td><td className="p-3 font-medium">{item.SafraNome}</td><td className="p-3 text-right">{Number(item.Toneladas).toLocaleString('pt-BR', { maximumFractionDigits: 3 })} t</td><td className="p-3 text-right">{moeda(item.CustoOperacional)}</td><td className="p-3 capitalize text-slate-600">{item.Origem}</td><td className="p-3 text-slate-600">{item.Observacao || '—'}</td></tr>)}{!carregando && !dados?.lancamentos.length && <tr><td className="p-8 text-center text-slate-400" colSpan={6}>Nenhum lançamento de produção.</td></tr>}</tbody></table></div></section></div>;
}

function Kpi({ icone, rotulo, valor, apoio }: { icone: React.ReactNode; rotulo: string; valor: string; apoio: string }) { return <div className="rounded-2xl border bg-white p-5"><div className="flex items-center gap-2 text-emerald-600">{icone}<span className="text-xs font-bold uppercase tracking-wide text-slate-500">{rotulo}</span></div><p className="mt-3 text-2xl font-bold text-slate-800">{valor}</p><p className="mt-1 text-xs text-slate-500">{apoio}</p></div>; }
