import { useCallback, useEffect, useState } from 'react';
import { KeyRound, Plus, ShieldCheck, UserRound } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

const API_URL = import.meta.env.VITE_API_URL ?? '';
const MODULOS = [{ id: 'logistica_frota', nome: 'Logística / Frota' }, { id: 'estoque', nome: 'Estoque' }, { id: 'producao_batata', nome: 'Produção / Batata' }, { id: 'manutencao', nome: 'Manutenção' }];
type Usuario = { UsuarioId: number; Nome: string; Email: string; TipoUsuario: 'admin' | 'comum'; Ativo: boolean; modulos: string[] };

export function GestaoUsuarios() {
  const { usuario } = useAuth();
  const [usuarios, setUsuarios] = useState<Usuario[]>([]); const [erro, setErro] = useState<string | null>(null); const [salvando, setSalvando] = useState(false);
  const [form, setForm] = useState({ nome: '', email: '', senha: '', tipoUsuario: 'comum', modulos: ['logistica_frota'] as string[] });
  const headers = { 'Content-Type': 'application/json', 'x-user-type': usuario?.tipoUsuario ?? '' };
  const carregar = useCallback(async () => { try { const resposta = await fetch(`${API_URL}/api/administracao/usuarios`, { headers }); const corpo = await resposta.json(); if (!resposta.ok) throw new Error(corpo.error); setUsuarios(corpo); } catch (falha) { setErro(falha instanceof Error ? falha.message : 'Falha ao carregar usuários.'); } }, [usuario?.tipoUsuario]);
  useEffect(() => { carregar(); }, [carregar]);
  const salvar = async (e: React.FormEvent) => { e.preventDefault(); setSalvando(true); setErro(null); try { const resposta = await fetch(`${API_URL}/api/administracao/usuarios`, { method: 'POST', headers, body: JSON.stringify(form) }); const corpo = await resposta.json(); if (!resposta.ok) throw new Error(corpo.error); setForm({ nome: '', email: '', senha: '', tipoUsuario: 'comum', modulos: ['logistica_frota'] }); await carregar(); } catch (falha) { setErro(falha instanceof Error ? falha.message : 'Falha ao criar usuário.'); } finally { setSalvando(false); } };
  const marcarModulo = (modulo: string) => setForm((atual) => ({ ...atual, modulos: atual.modulos.includes(modulo) ? atual.modulos.filter((item) => item !== modulo) : [...atual.modulos, modulo] }));
  return <div className="space-y-6 max-w-6xl"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Administração</p><h1 className="text-2xl font-bold text-slate-800">Gestão de usuários</h1><p className="text-sm text-slate-500 mt-1">Admins acessam todos os módulos. Usuários comuns acessam apenas os módulos selecionados.</p></div>
    {erro && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{erro}</div>}
    <form onSubmit={salvar} className="bg-white border rounded-2xl p-5 grid grid-cols-1 md:grid-cols-2 gap-4"><div className="md:col-span-2 flex items-center gap-2 font-bold text-slate-800"><Plus size={18} className="text-emerald-600"/> Novo usuário</div><input required value={form.nome} onChange={(e) => setForm({ ...form, nome: e.target.value })} placeholder="Nome completo" className="rounded-xl border px-3 py-2.5 text-sm"/><input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="E-mail" className="rounded-xl border px-3 py-2.5 text-sm"/><input required minLength={8} type="password" value={form.senha} onChange={(e) => setForm({ ...form, senha: e.target.value })} placeholder="Senha inicial (mín. 8 caracteres)" className="rounded-xl border px-3 py-2.5 text-sm"/><select value={form.tipoUsuario} onChange={(e) => setForm({ ...form, tipoUsuario: e.target.value })} className="rounded-xl border px-3 py-2.5 text-sm"><option value="comum">Usuário comum</option><option value="admin">Administrador</option></select><div className="md:col-span-2 flex flex-wrap gap-3">{MODULOS.map((modulo) => <label key={modulo.id} className={`flex items-center gap-2 rounded-lg border px-3 py-2 text-sm ${form.tipoUsuario === 'admin' ? 'opacity-50' : ''}`}><input type="checkbox" disabled={form.tipoUsuario === 'admin'} checked={form.tipoUsuario === 'admin' || form.modulos.includes(modulo.id)} onChange={() => marcarModulo(modulo.id)}/>{modulo.nome}</label>)}</div><div className="md:col-span-2"><button disabled={salvando} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><KeyRound size={16}/>{salvando ? 'Criando…' : 'Criar usuário'}</button></div></form>
    <section className="bg-white border rounded-2xl overflow-hidden"><div className="p-5 font-bold text-slate-800 flex items-center gap-2"><UserRound size={18} className="text-emerald-600"/> Usuários cadastrados</div><div className="overflow-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-500 text-left"><tr><th className="p-3">Nome</th><th className="p-3">E-mail</th><th className="p-3">Tipo</th><th className="p-3">Módulos</th></tr></thead><tbody>{usuarios.map((item) => <tr key={item.UsuarioId} className="border-t"><td className="p-3 font-medium">{item.Nome}</td><td className="p-3 text-slate-600">{item.Email}</td><td className="p-3"><span className="inline-flex items-center gap-1"><ShieldCheck size={14} className="text-emerald-600"/>{item.TipoUsuario === 'admin' ? 'Admin' : 'Comum'}</span></td><td className="p-3 text-xs text-slate-600">{item.TipoUsuario === 'admin' ? 'Todos os módulos' : item.modulos.join(', ')}</td></tr>)}</tbody></table></div></section></div>;
}
