import type { VercelRequest, VercelResponse } from '@vercel/node';
import { getMssqlPool } from './mssql.js';
import { exigirAcessoCustos } from './custosAuth.js';

// As consultas reproduzem o módulo de estoque recebido: dados reais do
// Sankhya (TGF*) e cada seção é independente para um schema incompleto não
// derrubar o painel inteiro.
const consultas = {
  ruptura: `SELECT TOP 100 P.CODPROD, P.DESCRPROD, P.REFERENCIA, L.DESCRLOCAL AS LOCAL, E.CODEMP AS EMPRESA, E.CONTROLE AS LOTE,
      E.ESTOQUE, P.ESTMIN AS MINIMO, P.ESTMAX AS MAXIMO, G.ESTMINGIR AS MINIMOSUGERIDO, G.DIASRUPTURA, G.PRODFALTA, G.PONTOPED AS PONTOPEDIDO
    FROM TGFPRO P LEFT JOIN TGFEST E ON E.CODPROD=P.CODPROD LEFT JOIN TGFLOC L ON L.CODLOCAL=E.CODLOCAL
      LEFT JOIN TGFGIR G ON G.CODPROD=P.CODPROD AND G.CODLOCAL=E.CODLOCAL AND G.CODEMP=E.CODEMP
    WHERE P.ATIVO='S' AND (G.PRODFALTA='S' OR (P.ESTMIN IS NOT NULL AND E.ESTOQUE<=P.ESTMIN))
    ORDER BY G.DIASRUPTURA DESC, E.ESTOQUE ASC`,
  semMovimentacao: `SELECT TOP 100 P.CODPROD, P.DESCRPROD, L.DESCRLOCAL AS LOCAL, G.CODEMP AS EMPRESA, G.GIRODIARIO, G.DIASSEMVENDA, G.ESTCUSTGER AS VALORESTOQUE
    FROM TGFGIR G JOIN TGFPRO P ON P.CODPROD=G.CODPROD LEFT JOIN TGFLOC L ON L.CODLOCAL=G.CODLOCAL
    WHERE P.ATIVO='S' AND G.DIASSEMVENDA>=90 ORDER BY G.DIASSEMVENDA DESC`,
  valor: `WITH Base AS (
      SELECT P.CODPROD, P.DESCRPROD, ISNULL(EST.ESTOQUE, 0) AS ESTOQUE, CUS.CUSTO, ISNULL(EST.ESTOQUE, 0)*CUS.CUSTO AS VALORTOTAL
      FROM TGFPRO P
      CROSS APPLY (SELECT SUM(E.ESTOQUE) AS ESTOQUE FROM TGFEST E WHERE E.CODPROD=P.CODPROD AND E.CODEMP=1) EST
      CROSS APPLY (SELECT TOP 1 COALESCE(C.CUSMEDICM,C.CUSSEMICM) AS CUSTO FROM TGFCUS C WHERE C.CODPROD=P.CODPROD AND C.CODEMP=1 ORDER BY C.DTATUAL DESC,C.NUNOTA DESC) CUS
      WHERE P.ATIVO='S' AND CUS.CUSTO IS NOT NULL
    ), Pareto AS (
      SELECT *, SUM(VALORTOTAL) OVER(ORDER BY VALORTOTAL DESC ROWS UNBOUNDED PRECEDING) / NULLIF(SUM(VALORTOTAL) OVER(),0) AS ACUMULADO FROM Base
    ) SELECT TOP 100 CODPROD, DESCRPROD, ESTOQUE, CUSTO, VALORTOTAL,
      CASE WHEN ACUMULADO<=.80 THEN 'A' WHEN ACUMULADO<=.95 THEN 'B' ELSE 'C' END AS CLASSEABC
    FROM Pareto ORDER BY VALORTOTAL DESC`,
  fornecedores: `SELECT TOP 100 PAR.NOMEPARC AS FORNECEDOR, AVG(CAST(ITC.CONFIABFORN AS DECIMAL(18,2))) AS CONFIABILIDADE,
      AVG(CAST(ITC.QUALATEND AS DECIMAL(18,2))) AS QUALIDADEATENDIMENTO, AVG(CAST(ITC.QUALPROD AS DECIMAL(18,2))) AS QUALIDADEPRODUTO,
      AVG(CAST(ITC.PRAZOENTREGA AS DECIMAL(18,2))) AS PRAZOMEDIO, COUNT(*) AS TOTALCOTACOES,
      SUM(CASE WHEN ITC.MELHOR='S' THEN 1 ELSE 0 END) AS TOTALVENCIDAS
    FROM TGFITC ITC LEFT JOIN TGFPAR PAR ON PAR.CODPARC=ITC.CODPARC GROUP BY PAR.NOMEPARC
    ORDER BY TOTALVENCIDAS DESC, CONFIABILIDADE DESC`,
  cotacoes: `SELECT TOP 100 COT.NUMCOTACAO, COT.DHINIC, COT.DHFINAL, COT.SITUACAO, USU.NOMEUSU AS COMPRADOR,
      (SELECT COUNT(*) FROM TGFITC I WHERE I.NUMCOTACAO=COT.NUMCOTACAO) AS TOTALITENS
    FROM TGFCOT COT LEFT JOIN TSIUSU USU ON USU.CODUSU=COT.CODUSUREQ
    WHERE COT.SITUACAO NOT IN ('F','C') ORDER BY COT.DHFINAL ASC`,
  giroProdutos: `SELECT TOP 100 P.CODPROD, P.DESCRPROD, P.MARCA, SUM(I.QTDNEG) AS QUANTIDADE, SUM(I.CUSTO*I.QTDNEG) AS VALOR
    FROM TGFITE I JOIN TGFPRO P ON P.CODPROD=I.CODPROD
    WHERE EXISTS (SELECT 1 FROM TGFCAB C WHERE C.NUNOTA=I.NUNOTA AND C.CODEMP=1 AND C.DTNEG>=DATEADD(DAY,-90,GETDATE())
      AND EXISTS (SELECT 1 FROM TGFTOP T WHERE T.CODTIPOPER=C.CODTIPOPER AND T.ATUALEST='B' AND T.DESCROPER LIKE '%VENDA%'))
    GROUP BY P.CODPROD,P.DESCRPROD,P.MARCA ORDER BY VALOR DESC`,
  kpis: `SELECT
    (SELECT COUNT(DISTINCT P.CODPROD) FROM TGFPRO P LEFT JOIN TGFEST E ON E.CODPROD=P.CODPROD LEFT JOIN TGFGIR G ON G.CODPROD=P.CODPROD AND G.CODLOCAL=E.CODLOCAL AND G.CODEMP=E.CODEMP WHERE P.ATIVO='S' AND (G.PRODFALTA='S' OR (P.ESTMIN IS NOT NULL AND E.ESTOQUE<=P.ESTMIN))) AS TOTALRUPTURA,
    (SELECT COUNT(DISTINCT G.CODPROD) FROM TGFGIR G JOIN TGFPRO P ON P.CODPROD=G.CODPROD WHERE P.ATIVO='S' AND G.DIASSEMVENDA>=90) AS TOTALSEMMOVIMENTACAO,
    (SELECT COUNT(*) FROM TGFCOT WHERE SITUACAO NOT IN ('F','C')) AS TOTALCOTACOES,
    (SELECT SUM(ISNULL(EST.ESTOQUE,0)*CUS.CUSTO) FROM TGFPRO P CROSS APPLY (SELECT SUM(E.ESTOQUE) AS ESTOQUE FROM TGFEST E WHERE E.CODPROD=P.CODPROD AND E.CODEMP=1) EST CROSS APPLY (SELECT TOP 1 COALESCE(C.CUSMEDICM,C.CUSSEMICM) AS CUSTO FROM TGFCUS C WHERE C.CODPROD=P.CODPROD AND C.CODEMP=1 ORDER BY C.DTATUAL DESC,C.NUNOTA DESC) CUS WHERE P.ATIVO='S' AND CUS.CUSTO IS NOT NULL) AS VALORTOTALESTOQUE,
    (SELECT SUM(I.CUSTO*I.QTDNEG) FROM TGFITE I WHERE EXISTS (SELECT 1 FROM TGFCAB C WHERE C.NUNOTA=I.NUNOTA AND C.CODEMP=1 AND C.DTNEG>=DATEADD(DAY,-90,GETDATE()) AND EXISTS (SELECT 1 FROM TGFTOP T WHERE T.CODTIPOPER=C.CODTIPOPER AND T.ATUALEST='B' AND T.DESCROPER LIKE '%VENDA%'))) AS CUSTOVENDAS90`
};

export async function painelEstoque(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'GET') return res.status(405).json({ error: 'Método não permitido' });
  if (!exigirAcessoCustos(req, res)) return;
  try {
    const pool = await getMssqlPool();
    const erros: Record<string, string> = {};
    const executar = async (nome: keyof typeof consultas) => {
      try { return (await pool.request().query(consultas[nome])).recordset; }
      catch (error) { erros[nome] = error instanceof Error ? error.message : 'Falha na consulta'; return []; }
    };
    const [ruptura, semMovimentacao, valor, fornecedores, cotacoes, giroProdutos, kpiRows] = await Promise.all([
      executar('ruptura'), executar('semMovimentacao'), executar('valor'), executar('fornecedores'), executar('cotacoes'), executar('giroProdutos'), executar('kpis'),
    ]);
    const kpis = kpiRows[0] ?? {};
    const giroEstoque90Dias = Number(kpis.CUSTOVENDAS90 ?? 0) / Number(kpis.VALORTOTALESTOQUE ?? 0) || null;
    res.status(200).json({ ruptura, semMovimentacao, valor, fornecedores, cotacoes, giroProdutos, kpis: { ...kpis, giroEstoque90Dias }, erros });
  } catch (error) {
    res.status(502).json({ error: 'Não foi possível conectar ao banco de dados de estoque.', detalhe: error instanceof Error ? error.message : undefined });
  }
}
