// Registro das queries do sistema já plugadas no mecanismo de override de querySistema.ts —
// uma por chave. Serve só pra pré-cadastrar (auto-seed) a entrada em dbo.ConfiguracaoIA na
// primeira vez que a tela de Treinamento de IA é aberta, pra quem já está com a coluna
// ChaveQuery migrada não precisar clicar em "Usar modelo" pra ver a query real que já está
// rodando — ela auto-cadastra INATIVA (Ativo=0): a query do código continua valendo até
// alguém revisar e ativar essa entrada de propósito.
//
// Pra conectar uma nova query a esse mecanismo: (1) trocar a query fixa no _lib correspondente
// por `await carregarQuerySql('chave', queryPadrao, valores)` (ver estoquePainel.ts), (2)
// adicionar uma entrada aqui com o mesmo texto (placeholders {{...}} no lugar dos valores
// interpolados) pra ela aparecer sozinha na tela assim que a migração rodar.
export const QUERIES_CONECTADAS: { chaveQuery: string; titulo: string; modulo: string; conteudo: string }[] = [
  {
    chaveQuery: 'estoque.fornecedores',
    titulo: 'Análise de Fornecedores — query real (Supplier Score)',
    modulo: 'estoque',
    conteudo: `WITH
    BASE AS (
      SELECT COT.NUMCOTACAO, COT.DHINIC, COT.CODEMP, ITC.CODPARC, PAR.NOMEPARC, PAR.RAZAOSOCIAL, PAR.CGC_CPF,
        ITC.CODPROD, PRO.DESCRPROD, PRO.CODGRUPOPROD, ITC.CONTROLE, ITC.CODLOCAL, ITC.DIFERENCIADOR,
        ITC.PRECO, ITC.QTDCOTADA, ITC.PRAZOENTREGA, ITC.SITUACAO, ITC.MELHOR,
        CASE WHEN COALESCE(ITC.PRECO,0)>0 THEN 1 ELSE 0 END AS RESPONDEU,
        CASE WHEN ITC.MELHOR='S' THEN 1 ELSE 0 END AS VENCEU
      FROM TGFCOT COT
        INNER JOIN TGFITC ITC ON ITC.NUMCOTACAO=COT.NUMCOTACAO
        INNER JOIN TGFPAR PAR ON PAR.CODPARC=ITC.CODPARC
        INNER JOIN TGFPRO PRO ON PRO.CODPROD=ITC.CODPROD
        INNER JOIN TGFGRU GRU ON GRU.CODGRUPOPROD=PRO.CODGRUPOPROD
      WHERE COT.DHINIC >= CONVERT(date,'{{dataInicio}}',23) AND COT.DHINIC < DATEADD(DAY,1,CONVERT(date,'{{dataFim}}',23))
        AND ITC.CABECALHO='N' AND ITC.CODPARC>0 AND {{filtroGrupo}}
    ),
    PRECO_ITEM AS (
      SELECT B.*,
        SUM(CASE WHEN B.PRECO>0 THEN B.PRECO ELSE 0 END) OVER (PARTITION BY B.NUMCOTACAO,B.CODPROD,B.CONTROLE,B.CODLOCAL,B.DIFERENCIADOR) AS SOMA_PRECOS_ITEM,
        SUM(CASE WHEN B.PRECO>0 THEN 1 ELSE 0 END) OVER (PARTITION BY B.NUMCOTACAO,B.CODPROD,B.CONTROLE,B.CODLOCAL,B.DIFERENCIADOR) AS QTD_PRECOS_ITEM
      FROM BASE B
    ),
    COMPARATIVO_ITEM AS (
      SELECT P.*, CASE WHEN P.PRECO>0 AND P.QTD_PRECOS_ITEM>1 THEN (P.SOMA_PRECOS_ITEM-P.PRECO)/NULLIF(P.QTD_PRECOS_ITEM-1,0) END AS PRECO_MEDIO_CONCORRENTES
      FROM PRECO_ITEM P
    ),
    INDICADORES AS (
      SELECT C.CODPARC, MAX(C.NOMEPARC) AS FORNECEDOR, MAX(C.RAZAOSOCIAL) AS RAZAOSOCIAL, MAX(C.CGC_CPF) AS CNPJ_CPF,
        COUNT(DISTINCT C.NUMCOTACAO) AS TOTAL_COTACOES,
        COUNT(DISTINCT CASE WHEN C.RESPONDEU=1 THEN C.NUMCOTACAO END) AS COTACOES_RESPONDIDAS,
        COUNT(DISTINCT CASE WHEN C.VENCEU=1 THEN C.NUMCOTACAO END) AS COTACOES_VENCIDAS,
        COUNT(DISTINCT CASE WHEN C.RESPONDEU=1 AND C.VENCEU=0 THEN C.NUMCOTACAO END) AS COTACOES_SEM_VITORIA,
        SUM(C.RESPONDEU) AS ITENS_COTADOS, SUM(C.VENCEU) AS ITENS_VENCIDOS,
        SUM(CASE WHEN C.RESPONDEU=1 AND C.VENCEU=0 THEN 1 ELSE 0 END) AS ITENS_NAO_VENCIDOS,
        ROUND(100*COUNT(DISTINCT CASE WHEN C.RESPONDEU=1 THEN C.NUMCOTACAO END)/NULLIF(COUNT(DISTINCT C.NUMCOTACAO),0),2) AS TAXA_RESPOSTA_PCT,
        ROUND(100*SUM(C.VENCEU)/NULLIF(SUM(C.RESPONDEU),0),2) AS TAXA_VITORIA_PCT,
        ROUND(100*COUNT(DISTINCT CASE WHEN C.VENCEU=1 THEN C.NUMCOTACAO END)/NULLIF(COUNT(DISTINCT CASE WHEN C.RESPONDEU=1 THEN C.NUMCOTACAO END),0),2) AS TAXA_VITORIA_COTACAO_PCT,
        ROUND(AVG(CASE WHEN C.RESPONDEU=1 THEN C.PRAZOENTREGA END),2) AS PRAZO_MEDIO_DIAS,
        COUNT(DISTINCT CASE WHEN C.RESPONDEU=1 THEN C.CODPROD END) AS PRODUTOS_DISTINTOS,
        COUNT(DISTINCT CASE WHEN C.RESPONDEU=1 THEN C.CODGRUPOPROD END) AS CATEGORIAS_DISTINTAS,
        ROUND(AVG(CASE WHEN C.PRECO>0 THEN C.PRECO END),4) AS PRECO_MEDIO_FORNECEDOR,
        ROUND(AVG(C.PRECO_MEDIO_CONCORRENTES),4) AS PRECO_MEDIO_CONCORRENTES,
        ROUND(AVG(CASE WHEN C.PRECO>0 AND C.PRECO_MEDIO_CONCORRENTES>0 THEN (C.PRECO_MEDIO_CONCORRENTES-C.PRECO)/C.PRECO_MEDIO_CONCORRENTES*100 END),2) AS COMPETITIVIDADE_PRECO_MEDIA_PCT,
        ROUND(100*SUM(CASE WHEN C.PRECO>0 AND C.PRECO_MEDIO_CONCORRENTES>0 AND COALESCE(C.QTDCOTADA,0)>0 THEN (C.PRECO_MEDIO_CONCORRENTES-C.PRECO)*C.QTDCOTADA ELSE 0 END)/
          NULLIF(SUM(CASE WHEN C.PRECO>0 AND C.PRECO_MEDIO_CONCORRENTES>0 AND COALESCE(C.QTDCOTADA,0)>0 THEN C.PRECO_MEDIO_CONCORRENTES*C.QTDCOTADA ELSE 0 END),0),2) AS COMPETITIVIDADE_PRECO_PCT,
        SUM(CASE WHEN C.PRECO>0 AND C.PRECO_MEDIO_CONCORRENTES>0 THEN 1 ELSE 0 END) AS ITENS_COM_COMPARACAO_PRECO,
        ROUND(SUM(CASE WHEN C.VENCEU=1 AND C.PRECO>0 AND C.PRECO_MEDIO_CONCORRENTES>0 AND COALESCE(C.QTDCOTADA,0)>0 THEN (C.PRECO_MEDIO_CONCORRENTES-C.PRECO)*C.QTDCOTADA ELSE 0 END),2) AS ECONOMIA_LIQUIDA_VS_MEDIA,
        ROUND(SUM(CASE WHEN C.VENCEU=1 AND C.PRECO>0 AND C.PRECO_MEDIO_CONCORRENTES>C.PRECO AND COALESCE(C.QTDCOTADA,0)>0 THEN (C.PRECO_MEDIO_CONCORRENTES-C.PRECO)*C.QTDCOTADA ELSE 0 END),2) AS ECONOMIA_POSITIVA_VS_MEDIA,
        MIN(C.DHINIC) AS PRIMEIRA_COTACAO_PERIODO, MAX(C.DHINIC) AS ULTIMA_COTACAO
      FROM COMPARATIVO_ITEM C GROUP BY C.CODPARC
    ),
    FORNECEDORES_VALIDOS AS (SELECT I.* FROM INDICADORES I WHERE I.COTACOES_RESPONDIDAS>0),
    SCORE_COMPONENTES AS (
      SELECT F.*,
        CASE WHEN F.TAXA_VITORIA_PCT IS NOT NULL THEN ROUND(100*CUME_DIST() OVER (PARTITION BY CASE WHEN F.TAXA_VITORIA_PCT IS NULL THEN 1 ELSE 0 END ORDER BY F.TAXA_VITORIA_PCT),2) END AS SCORE_VITORIA,
        CASE WHEN COALESCE(F.COMPETITIVIDADE_PRECO_PCT,F.COMPETITIVIDADE_PRECO_MEDIA_PCT) IS NOT NULL THEN ROUND(100*CUME_DIST() OVER (PARTITION BY CASE WHEN COALESCE(F.COMPETITIVIDADE_PRECO_PCT,F.COMPETITIVIDADE_PRECO_MEDIA_PCT) IS NULL THEN 1 ELSE 0 END ORDER BY COALESCE(F.COMPETITIVIDADE_PRECO_PCT,F.COMPETITIVIDADE_PRECO_MEDIA_PCT)),2) END AS SCORE_COMPETITIVIDADE,
        CASE WHEN F.PRAZO_MEDIO_DIAS IS NOT NULL THEN ROUND(100*CUME_DIST() OVER (PARTITION BY CASE WHEN F.PRAZO_MEDIO_DIAS IS NULL THEN 1 ELSE 0 END ORDER BY F.PRAZO_MEDIO_DIAS DESC),2) END AS SCORE_PRAZO,
        ROUND(100*CUME_DIST() OVER (ORDER BY F.PRODUTOS_DISTINTOS),2) AS SCORE_COBERTURA,
        ROUND(100*CUME_DIST() OVER (ORDER BY F.TOTAL_COTACOES),2) AS SCORE_VOLUME
      FROM FORNECEDORES_VALIDOS F
    ),
    SCORE_FINAL AS (
      SELECT S.*, ROUND((
          CASE WHEN S.SCORE_VITORIA IS NOT NULL THEN S.SCORE_VITORIA*35 ELSE 0 END +
          CASE WHEN S.SCORE_COMPETITIVIDADE IS NOT NULL THEN S.SCORE_COMPETITIVIDADE*30 ELSE 0 END +
          CASE WHEN S.SCORE_PRAZO IS NOT NULL THEN S.SCORE_PRAZO*15 ELSE 0 END +
          CASE WHEN S.SCORE_COBERTURA IS NOT NULL THEN S.SCORE_COBERTURA*10 ELSE 0 END +
          CASE WHEN S.SCORE_VOLUME IS NOT NULL THEN S.SCORE_VOLUME*10 ELSE 0 END
        )/NULLIF(
          CASE WHEN S.SCORE_VITORIA IS NOT NULL THEN 35 ELSE 0 END +
          CASE WHEN S.SCORE_COMPETITIVIDADE IS NOT NULL THEN 30 ELSE 0 END +
          CASE WHEN S.SCORE_PRAZO IS NOT NULL THEN 15 ELSE 0 END +
          CASE WHEN S.SCORE_COBERTURA IS NOT NULL THEN 10 ELSE 0 END +
          CASE WHEN S.SCORE_VOLUME IS NOT NULL THEN 10 ELSE 0 END, 0),2) AS SUPPLIER_SCORE
      FROM SCORE_COMPONENTES S
    ),
    CLASSIFICADO AS (
      SELECT S.*,
        CASE WHEN S.SUPPLIER_SCORE>=85 THEN 'Excelente' WHEN S.SUPPLIER_SCORE>=70 THEN 'Bom' WHEN S.SUPPLIER_SCORE>=50 THEN 'Regular' ELSE 'Atencao' END AS FAIXA_SUPPLIER_SCORE,
        CASE WHEN COALESCE(S.COMPETITIVIDADE_PRECO_PCT,S.COMPETITIVIDADE_PRECO_MEDIA_PCT)>0 THEN 'Mais competitivo' WHEN COALESCE(S.COMPETITIVIDADE_PRECO_PCT,S.COMPETITIVIDADE_PRECO_MEDIA_PCT)<0 THEN 'Mais caro' ELSE 'Neutro' END AS STATUS_COMPETITIVIDADE
      FROM SCORE_FINAL S
    ),
    RANKING AS (
      SELECT C.*, DENSE_RANK() OVER (ORDER BY C.SUPPLIER_SCORE DESC, C.TAXA_VITORIA_PCT DESC, COALESCE(C.COMPETITIVIDADE_PRECO_PCT,C.COMPETITIVIDADE_PRECO_MEDIA_PCT) DESC, C.PRAZO_MEDIO_DIAS ASC, C.TOTAL_COTACOES DESC) AS RANKING_GERAL
      FROM CLASSIFICADO C
    ),
    KPI_GERAIS AS (
      SELECT COUNT(*) AS FORNECEDORES_ATIVOS_PERIODO, MIN(R.PRAZO_MEDIO_DIAS) AS MELHOR_PRAZO_MEDIO_PERIODO,
        MAX(R.TAXA_VITORIA_PCT) AS MAIOR_TAXA_VITORIA_PERIODO, SUM(R.ECONOMIA_POSITIVA_VS_MEDIA) AS ECONOMIA_ACUMULADA_PERIODO,
        (SELECT COUNT(DISTINCT CASE WHEN B.RESPONDEU=1 THEN B.CODGRUPOPROD END) FROM BASE B) AS CATEGORIAS_ATENDIDAS_PERIODO
      FROM RANKING R
    )
    SELECT TOP 2000
      R.RANKING_GERAL, CASE WHEN R.RANKING_GERAL=1 THEN 'S' ELSE 'N' END AS MELHOR_FORNECEDOR_PERIODO,
      R.CODPARC, R.FORNECEDOR, R.RAZAOSOCIAL, R.CNPJ_CPF,
      R.SUPPLIER_SCORE, R.FAIXA_SUPPLIER_SCORE, R.SCORE_VITORIA, R.SCORE_COMPETITIVIDADE, R.SCORE_PRAZO, R.SCORE_COBERTURA, R.SCORE_VOLUME,
      R.TOTAL_COTACOES, R.COTACOES_RESPONDIDAS, R.COTACOES_VENCIDAS, R.COTACOES_SEM_VITORIA,
      R.ITENS_COTADOS, R.ITENS_VENCIDOS, R.ITENS_NAO_VENCIDOS,
      R.TAXA_RESPOSTA_PCT, R.TAXA_VITORIA_PCT, R.TAXA_VITORIA_COTACAO_PCT,
      R.PRAZO_MEDIO_DIAS, R.PRODUTOS_DISTINTOS, R.CATEGORIAS_DISTINTAS,
      R.PRECO_MEDIO_FORNECEDOR, R.PRECO_MEDIO_CONCORRENTES, R.COMPETITIVIDADE_PRECO_PCT, R.COMPETITIVIDADE_PRECO_MEDIA_PCT, R.STATUS_COMPETITIVIDADE,
      R.ITENS_COM_COMPARACAO_PRECO, R.ECONOMIA_LIQUIDA_VS_MEDIA, R.ECONOMIA_POSITIVA_VS_MEDIA,
      R.PRIMEIRA_COTACAO_PERIODO, R.ULTIMA_COTACAO,
      K.FORNECEDORES_ATIVOS_PERIODO, K.MELHOR_PRAZO_MEDIO_PERIODO, K.MAIOR_TAXA_VITORIA_PERIODO, K.CATEGORIAS_ATENDIDAS_PERIODO, K.ECONOMIA_ACUMULADA_PERIODO
    FROM RANKING R CROSS JOIN KPI_GERAIS K
    ORDER BY R.RANKING_GERAL, R.SUPPLIER_SCORE DESC, R.FORNECEDOR`,
  },
];
